### PR TITLE
Feat/sidebar

### PR DESCRIPTION
**Pull request by tillwenke**
did it the easy way.
could you make the menu appear by default when accessing the site? @bopjesvla

### CODE REVIEW

**Comment by bopjesvla** [comment]
I have quite a few comments. Don't be disparaged, you're on the right track.

> could you make the menu appear by default when accessing the site?

That seems ill-advised, most people visiting just want to use the map.

We can move the credits to the menu, and put the menu button in the bottom-right corner.

Another thing: a menu shouldn't have this much unstructured text. Also, URLs shouldn't be shown as plain text. They should be links with a human-readable label. I like the use of the Github icon though.

Maybe add the following sections:

Credits (everything in the footer)

Links (Recent changes, GHICON Contribute, GHICON Report bugs)

Maybe a changelog?

I think there were other things we held off because we didn't have a menu, it might be worth it to search the issues for "menu"

**Comment by tillwenke** [comment]
done.
@bopjesvla you can make any changes that you find more visually appealing : )

**Comment by bopjesvla** [comment]
If put in the top-right, the menu touches the search bar on small screens, even though it looks good on a big screen. I'm moving the menu button to the horizontal row of buttons for now, lmk if you find a better place

**Comment by bopjesvla** [comment]
Merged :)

**Pull request merged**
