### PR TITLE
Fix/dashboard

### PR DESCRIPTION
**Pull request by tillwenke**

### CODE REVIEW

**Comment by tillwenke** [comment]
We also have an issue here.
@bopjesvla any ideas why the dashboard does not show the most recent activity. For me September does not show any bars.
Maybe it is in the cronjob or the db we connect to...

**Comment by tillwenke** [comment]
I tested with dumps.sqlite locally and it looks good.

**Comment by bopjesvla** [comment]
>  Maybe it is in the cronjob or the db we connect to...

Oh yeah I still have to do this

**Comment by bopjesvla** [comment]
merged using git but github doesn't show it here somehow

**Pull request closed without merging**
