### PR TITLE
Feat/dash

### PR DESCRIPTION
**Pull request by tillwenke**
there is a first suggestion for a dashboard at /dash
@bopjesvla

### CODE REVIEW

**Comment by bopjesvla** [comment]
This doesn't have to be live, I'd create a separate file that generates a webpage. Something like dump.py that can be added to the cronjob, but instead it generates a page. This way, you don't have to generate the dashboard each time it's loaded.

**Comment by tillwenke** [comment]
good point. already thought it is not ideal as it is.

**Comment by tillwenke** [comment]
done

**Comment by bopjesvla** [comment]
Code looks good, will try when I have internet at my new place

**Pull request merged**
