### PR TITLE
give duplicate reporting more visibility

### PR DESCRIPTION
**Pull request by tillwenke**

### CODE REVIEW

**Comment by tillwenke** [comment]
just a little more appealing to take an action

**Comment by tillwenke** [comment]
Id like to only have a symbol for it but.
1) tough to find one that is clear
2) mobile users cannot hover to see what it does

**Comment by bderui** [comment]
Most users open a spot to see the details, not to report it, so it makes sense to put the reporting function last. Only when a spot has a lot of comments, this becomes annoying, but most duplicate spots don't have that many comments

**Comment by bopjesvla** [comment]
Most people who open a spot want to see the details, not report it. Only when a spot has a lot of comments, it might become annoying to find the report button, but duplicate spots usually don't have many comments

**Comment by bopjesvla** [comment]
I think the button is already very visible and there are other reasons people don't use it: they don't want to or their English isn't good enough to understand the label

**Comment by bderui** [comment]
Merge into nearby spot

**Comment by bderui** [comment]
(work account)

**Comment by tillwenke** [comment]
imo thats quite clean. 
image

dont have too hard feelings about it if you d like to move it to the bottom instead

**Comment by bopjesvla** [comment]
In the current layout, I'm pretty sure my phone is not big enough to display all of that on one line. I'm not sure "Report duplicate" is clear enough without context.

**Comment by bopjesvla** [comment]
We agreed to put the new actions above each other at the bottom

**Pull request closed without merging**
