### PR TITLE
reporting spots that are completely wrong and should not exist

### PR DESCRIPTION
**Pull request by tillwenke**
quite similar to duplicate reporting

### CODE REVIEW

**Comment by tillwenke** [comment]
review after #72

**Comment by bderui** [comment]
This makes sense, but this should probably be subject to a real review instead of the allow-by-default we're using for all other actions. That or we implement optional user accounts first, which people have been asking about anyway

**Comment by tillwenke** [comment]
the argument applies to duplicate spots as well. doesnt it

**Comment by bopjesvla** [comment]
Dupes can only be reported for nearby spots, we'll wait for abuse before requiring a review there

**Comment by bopjesvla** [comment]
We could also make this a user-only action once we have user accounts

**Pull request merged**
